# WEB PROPERTIES
server:
  port: 8088

spring:

  # DATASOURCE
  datasource:
    url: 'jdbc:oracle:thin:@192.168.1.36:1521/hyora'
    username: 'ESTAR'
    password: 'ESTAR'
    driver-class-name: 'oracle.jdbc.OracleDriver'

  # redis
  redis:
    database: 11
    host: 192.168.1.37
    port: 6379
    password: Test123