# https://docs.spring.io/spring-boot/docs/2.0.4.RELEASE/reference/htmlsingle/#common-application-properties
server:
  servlet:
    context-path: /evcs/v1

# SPRING
spring:
  profiles:
    active: dev

  # 出现错误时抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  # 资源文件不建立映射
  resources:
    add-mappings: false

  # JACKSON
  jackson:
    property-naming-strategy: 'UPPER_CAMEL_CASE'
    date-format: yyyy-MM-dd HH:mm:ss

  # jpa
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# LOGGING
logging:
  config: 'classpath:logback.xml'