# https://docs.spring.io/spring-boot/docs/1.5.9.RELEASE/reference/htmlsingle/#common-application-properties
server:
  servlet:
    context-path: /evcs/v1

# SPRING
spring:
  profiles:
    active: dev

  # DATASOURCE
  datasource:
    url: 'jdbc:oracle:thin:@192.168.1.156:1521/xgsid.xg156.com'
    username: 'ESTAR'
    password: 'ESTAR'
    driver-class-name: 'oracle.jdbc.OracleDriver'

  # 出现错误时抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  # 资源文件不建立映射
  resources:
    add-mappings: false

  # JACKSON
  jackson:
    property-naming-strategy: 'UPPER_CAMEL_CASE'
    date-format: yyyy-MM-dd HH:mm:ss

  # redis
  redis:
    database: 11
    host: 192.168.1.156
    port: 6379

  # jpa
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


# LOGGING
logging:
  config: 'classpath:logback.xml'